import { ProductsType } from "@/lib/types";

export const popularProducts: ProductsType = [
	{
		id: 101,
		name: "Organic Non Bridal Cone",
		price: 50.0,
		images: [
			"/products/NonBridal-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Organic Mehedi"],
		inStock: false,
		badge: "25g",
		rating: 4.5,
		reviewsCount: 12,
		shortDescription: [
			"Net Wet : 25-27 gm (each cone)",
			"Length : 7 Inch",
			"BSTI certified 100% Halal Organic raw materials.",
		],
		longDescription:
			"Hand crafted henna paste is made with the highest quality ingredients available. We believe if you begin with an excellent ingredient you will have excellent results! And also making sure a completely halal and chemical free henna cone.",
	},
	{
		id: 102,
		name: "Organic Henna Cone - Small",
		price: 100.0,
		images: [
			"/products/small-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Organic Henna Cone"],
		inStock: true,
		badge: "20-22g",
		rating: 5,
		reviewsCount: 24,
		shortDescription: [
			"Net Wet : 20-22 gm (each cone)",
			"Length : 6.5 Inch",
			"Perfect for small and detailed designs.",
		],
		longDescription:
			"Our small organic henna cones are perfect for quick applications and intricate, delicate designs. Hand crafted with 100% natural ingredients to ensure a rich and long-lasting stain without any harsh chemicals.",
	},
	{
		id: 103,
		name: "Organic Henna Cone - Medium",
		price: 120.0,
		images: [
			"/products/medium-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Organic Henna Cone", "Organic Mehedi"],
		inStock: true,
		badge: "25-26g",
		rating: 4.8,
		reviewsCount: 45,
		sku: "330aee",
		shortDescription: [
			"Net Wet : 25-26 gm (each cone)",
			"Length : 7 Inch",
			"BSTI certified 100% Halal Organic raw materials.",
		],
		longDescription:
			"The medium-sized cone is our most popular choice, offering the perfect balance between quantity and ease of use. It is made with triple-sifted henna powder and premium essential oils for a stunning dark stain.",
	},
	{
		id: 104,
		name: "Organic Henna Cone - Large",
		price: 150.0,
		images: [
			"/products/large-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Organic Henna Cone"],
		inStock: true,
		badge: "32-33g",
		rating: 5,
		reviewsCount: 30,
		shortDescription: ["Net Wet : 32-33 gm (each cone)", "Length : 8 Inch", "Ideal for heavy bridal designs."],
		longDescription:
			"Designed specifically for professional artists and bridal applications, this large henna cone contains extra paste so you do not have to switch cones frequently while working on heavy, elaborate designs.",
	},
	{
		id: 105,
		name: "Premium Bridal Henna Set",
		price: 450.0,
		images: [
			"/products/large-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Special Combo"],
		inStock: true,
		badge: "5 Cones",
		rating: 4.9,
		reviewsCount: 18,
		shortDescription: [
			"Includes 5 premium large cones",
			"Comes with aftercare oil and sealant",
			"100% natural and chemical free",
		],
		longDescription:
			"Make your special day even more memorable with our Premium Bridal Henna Set. This package includes 5 large organic cones, a bottle of henna sealant spray, and aftercare balm to ensure the darkest possible stain for your wedding.",
	},
	{
		id: 106,
		name: "Organic Mehedi Paste (Jar)",
		price: 250.0,
		images: [
			"/products/large-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Organic Mehedi"],
		inStock: true,
		badge: "150g",
		rating: 4.7,
		reviewsCount: 8,
		shortDescription: [
			"Net Wet: 150g",
			"Pure organic powder mixed with essential oils",
			"Ready to use paste for cones or direct application",
		],
		longDescription:
			"Our organic mehedi paste comes in a convenient, airtight jar. It is perfectly mixed and ready to use. You can easily roll your own cones with this paste or use it directly for hair conditioning and coloring.",
	},
];

export const bestSellerProducts: ProductsType = [
	{
		id: 201,
		name: "Hair Color 100gm",
		price: 300.0,
		images: [
			"/products/hair-pack.jpg",
			"/products/hair-review-1.jpg",
			"/products/hair-review-2.jpg",
			"/products/hair-review-3.png",
			"/products/hair-review-4.png",
		],
		categories: ["Hair Care", "Hair Serum"],
		inStock: true,
		badge: "100 ML",
		rating: 5,
		reviewsCount: 50,
		shortDescription: ["Volume: 100 ML", "Frizz control and shine enhancer", "Non-sticky, lightweight formula"],
		longDescription:
			"Experience the magic of nature with our organic hair serum. Infused with argan and jojoba extracts, it instantly tames frizz, adds a beautiful shine, and protects your hair from environmental damage without making it greasy.",
	},
	{
		id: 202,
		name: "Hair Color 110gm",
		price: 350.0,
		images: [
			"/products/hair-pack.jpg",
			"/products/hair-review-1.jpg",
			"/products/hair-review-2.jpg",
			"/products/hair-review-3.png",
			"/products/hair-review-4.png",
		],
		categories: ["Hair Care", "Hair Oil"],
		inStock: true,
		badge: "110 ML",
		rating: 4.8,
		reviewsCount: 42,
		shortDescription: ["Volume: 200 ML", "Reduces hair fall significantly", "Promotes new hair growth"],
		longDescription:
			"A powerful blend of 15+ natural herbs and cold-pressed oils designed to stop hair fall and promote new hair growth. Massage gently onto the scalp twice a week for the best and most visible results.",
	},
	{
		id: 203,
		name: "Magic Hair Serum 100ml",
		price: 150.0,
		images: [
			"/products/hair-serum-100.jpg",
			"/products/hair-review-2.jpg",
			"/products/hair-review-3.png",
			"/products/hair-review-4.png",
		],
		categories: ["Hair Care", "Hair Pack"],
		inStock: true,
		badge: "100g",
		rating: 4.6,
		reviewsCount: 15,
		shortDescription: ["Net Weight: 200g", "Deep conditioning treatment", "Repairs damaged and split ends"],
		longDescription:
			"Revitalize your dull and damaged hair with our organic hair pack. Made with Amla, Shikakai, and Bhringraj, this pack acts as a deep conditioning treatment that strengthens roots and adds volume to your hair.",
	},
	{
		id: 204,
		name: "Magic Hair Serum 110ml",
		price: 180.0,
		images: [
			"/products/hair-serum-110.jpg",
			"/products/hair-review-2.jpg",
			"/products/hair-review-3.png",
			"/products/hair-review-4.png",
		],
		categories: ["Henna Powder"],
		inStock: true,
		badge: "110g",
		rating: 4.9,
		reviewsCount: 35,
		shortDescription: [
			"Net Weight: 100g",
			"Triple shifted extra fine powder",
			"Perfect for hair dyeing and body art",
		],
		longDescription:
			"Our pure henna powder is triple-sifted to ensure a smooth, lump-free paste. Cultivated in the finest farms, it provides a rich reddish-brown tone for hair and a deep stain for body art. 100% natural.",
	},
	{
		id: 205,
		name: "Anti-Hairfall Oil Mix",
		price: 400.0,
		images: [
			"/products/hair-serum-110.jpg",
			"/products/hair-review-2.jpg",
			"/products/hair-review-3.png",
			"/products/hair-review-4.png",
		],
		categories: ["Oil"],
		inStock: true,
		badge: "150 ML",
		rating: 4.5,
		reviewsCount: 10,
		shortDescription: ["Volume: 150 ML", "Enriched with Onion and Castor oil", "Strengthens hair follicles"],
		longDescription:
			"Say goodbye to hair thinning with our specialized Anti-Hairfall Oil Mix. Formulated with potent onion extract and Jamaican black castor oil, it deeply penetrates the scalp to awaken dormant hair follicles.",
	},
	{
		id: 206,
		name: "Premium Nail Cone (Red)",
		price: 60.0,
		images: [
			"/products/hair-serum-110.jpg",
			"/products/hair-review-2.jpg",
			"/products/hair-review-3.png",
			"/products/hair-review-4.png",
		],
		categories: ["Nail Cone"],
		inStock: true,
		badge: "10g",
		rating: 4.7,
		reviewsCount: 22,
		shortDescription: ["Net Wet: 10g", "Instant deep red color", "Chemical free and Wudu friendly"],
		longDescription:
			"Get beautiful, vibrant red nails instantly with our premium nail cone. It is formulated with natural extracts to be completely safe for your nails while providing a long-lasting, water-permeable color.",
	},
];

export const randomProducts: ProductsType = [
	{
		id: 301,
		name: "Eid Combo 1",
		price: 450.0,
		images: ["/products/eid-1.jpg"],
		categories: ["Special Combo"],
		inStock: true,
		rating: 5,
		reviewsCount: 11,
		shortDescription: ["3 Medium Cones + 2 Large Cones", "Includes essential oil 10ml", "Perfect Eid gift package"],
		longDescription:
			"Celebrate Eid with our exclusive Combo 4 package. This bundle includes our best-selling medium and large cones along with a stain-enhancing essential oil, packed beautifully to serve as a perfect gift.",
	},
	{
		id: 302,
		name: "Eid Combo 2",
		price: 360.0,
		images: ["/products/eid-2.jpg"],
		categories: ["Special Combo"],
		inStock: true,
		rating: 4.8,
		reviewsCount: 25,
		shortDescription: ["4 Small Cones + 1 Nail Cone", "Budget friendly festival pack", "100% Organic"],
		longDescription:
			"The Eid Combo 1 is designed for personal use and quick application. With 4 organic small cones and 1 bright red nail cone, it provides everything you need to get festival-ready in no time.",
	},
	{
		id: 303,
		name: "Eid Combo 3",
		price: 500.0,
		images: ["/products/eid-3.jpg"],
		categories: ["Special Combo"],
		inStock: true,
		rating: 5,
		reviewsCount: 19,
		shortDescription: ["5 Medium Cones + Henna Sealant", "Ensures extra dark stain", "Great value for money"],
		longDescription:
			"Maximize your henna stain with Eid Combo 2. The included henna sealant spray locks the dried paste onto your skin, allowing it to stay on longer and develop an incredibly deep, rich color.",
	},
	{
		id: 304,
		name: "Eid Combo 4",
		price: 600.0,
		images: ["/products/eid-4.jpg"],
		categories: ["Special Combo"],
		inStock: true,
		rating: 4.9,
		reviewsCount: 33,
		shortDescription: ["6 Large Cones + Aftercare Balm", "Ideal for families", "Premium quality paste"],
		longDescription:
			"Got a big family to decorate this Eid? Combo 3 offers 6 large cones that are sufficient for multiple heavy designs. The protective aftercare balm ensures your stain is protected from water and fades slower.",
	},
	{
		id: 305,
		name: "Hair Care Ultimate Combo",
		price: 850.0,
		images: ["/products/eid-4.jpg"],
		categories: ["Special Combo", "Hair Care"],
		inStock: true,
		badge: "Save 10%",
		rating: 4.6,
		reviewsCount: 7,
		shortDescription: [
			"Includes Hair Oil, Serum & Hair Pack",
			"Complete organic hair routine",
			"Stops hair fall & adds shine",
		],
		longDescription:
			"Transform your hair with our Ultimate Hair Care Combo. This three-step routine includes our herbal hair oil for nourishment, the organic hair pack for repair, and the hair serum for that perfect finishing shine.",
	},
	{
		id: 306,
		name: "Bridal Mehedi Package",
		price: 1200.0,
		images: ["/products/eid-4.jpg"],
		categories: ["Special Combo"],
		inStock: true,
		badge: "Best Value",
		rating: 5,
		reviewsCount: 14,
		shortDescription: [
			"10 Large Cones + 2 Essential Oils + Balm",
			"Professional artist bundle",
			"Guaranteed dark mahogany stain",
		],
		longDescription:
			"The ultimate arsenal for any bridal henna artist. This massive package includes everything needed to execute flawless, dark-staining bridal artwork that will leave the bride and guests amazed.",
	},
];

export const featuredProducts: ProductsType = [
	{
		id: 401,
		name: "Cut Cellophane paper 50pcs",
		price: 100.0,
		images: ["/products/cut-cellophane-paper-50pcs.png", "/products/cut-cellophane-paper-50pcs-1.jpg"],
		categories: ["Accessories"],
		inStock: false,
		badge: "1 Sheet",
		shortDescription: [
			"Reusable Arabic design sticker",
			"Easy peel-and-stick application",
			"Perfect for beginners",
		],
		longDescription:
			"Achieve professional-looking henna designs at home without any artistic skills. Simply stick the stencil onto your hand, apply the henna paste over it, wait for it to dry, and peel off for a flawless pattern.",
	},
	{
		id: 402,
		name: "Raw Eucalyptus Essential Oil 100ML",
		price: 200.0,
		images: [
			"/products/raw-eucalyptus-essential-oil-100ml.png",
			"/products/raw-eucalyptus-essential-oil-100ml-1.png",
			"/products/raw-eucalyptus-essential-oil-100ml-2.png",
		],
		categories: ["Oil"],
		inStock: false,
		badge: "50 ML",
		shortDescription: [
			"100% Pure Essential Tea Tree Oil",
			"Enhances mehedi stain darkness",
			"Aromatic and safe for skin",
		],
		longDescription:
			"Add a few drops of our pure essential tea tree oil to your homemade henna paste. The active terpineols in the oil react with the lawsone dye in henna to drastically darken the stain.",
	},
	{
		id: 103,
		name: "Organic Henna Cone - Medium",
		price: 120.0,
		images: [
			"/products/medium-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Organic Henna Cone", "Organic Mehedi"],
		inStock: true,
		badge: "25-26g",
		rating: 4.8,
		reviewsCount: 45,
		sku: "330aee",
		shortDescription: [
			"Net Wet : 25-26 gm (each cone)",
			"Length : 7 Inch",
			"BSTI certified 100% Halal Organic raw materials.",
		],
		longDescription:
			"The medium-sized cone is our most popular choice, offering the perfect balance between quantity and ease of use. It is made with triple-sifted henna powder and premium essential oils for a stunning dark stain.",
	},
	{
		id: 404,
		name: "Bridal Box 1",
		price: 1150.0,
		images: ["/products/bridal-box-1.png", "/products/bridal-box-2.png"],
		categories: ["Perfume", "Oil"],
		inStock: false,
		badge: "30 ML",
		shortDescription: [
			"Premium Eucalyptus extract",
			"Darkens henna stain naturally",
			"Refreshing and cooling sensation",
		],
		longDescription:
			"Our premium Eucalyptus oil is extracted using the finest steam distillation methods. It is the traditional secret ingredient used by professionals to achieve a dark, rich, and long-lasting henna stain.",
	},
	{
		id: 405,
		name: "Tape Dispenser",
		price: 150.0,
		images: [
			"/products/medium-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Tape Dispenser"],
		inStock: true,
		rating: 4.5,
		reviewsCount: 5,
		shortDescription: ["Heavy duty plastic material", "Ultra-sharp cutting blade", "Holds standard tape sizes"],
		longDescription:
			"A durable and handy tape dispenser for all your packaging, crafting, and cone-rolling needs. Features a sharp, rust-resistant blade for clean and easy cuts, saving you time and effort.",
	},
	{
		id: 406,
		name: "Cellophane Paper Roll",
		price: 100.0,
		images: [
			"/products/medium-cone.jpg",
			"/products/cone-2.jpg",
			"/products/cone-3.jpg",
			"/products/cone-review.png",
		],
		categories: ["Cellophane Paper"],
		inStock: true,
		badge: "1 Roll",
		rating: 4.8,
		reviewsCount: 16,
		shortDescription: [
			"Pre-cut cello sheets for cone rolling",
			"Transparent & highly flexible",
			"Prevents paste leakage",
		],
		longDescription:
			"Create your own perfect, pin-hole sized henna cones with our high-quality cellophane paper rolls. The material is sufficiently flexible to roll tight tips, yet strong enough to prevent bursting during heavy squeezing.",
	},
];
